# Generated by Django 5.2.1 on 2025-05-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='nome_veiculo',
            field=models.CharField(default='Sem Nome', max_length=100),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
