# Generated by Django 5.2.1 on 2025-05-28 14:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0002_anuncio_ativo_anuncio_nome_veiculo_anuncio_preco'),
        ('veiculo', '0002_veiculo_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='nome_veiculo',
        ),
        migrations.AddField(
            model_name='anuncio',
            name='anunciante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 28, 14, 23, 44, 756555, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='veiculo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='veiculo.veiculo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='preco',
            field=models.TextField(),
        ),
    ]
