# Generated by Django 5.2.1 on 2025-05-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncio', '0003_remove_anuncio_nome_veiculo_anuncio_anunciante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
